import React, { useEffect, useState } from 'react';
import { Helmet } from 'react-helmet';
import { useSearchParams } from 'react-router-dom';

/* ─── /leadssheet ───
 * Internal download page for the all-forms Excel workbook (Apply Now,
 * Contact Us, Enquire Now, Lead Popup — one sheet each).
 *
 *   https://maieuticedutech.com/leadssheet?key=<LEADS_SHEET_KEY>
 *     → hands the browser straight to the backend export and the file downloads.
 *   https://maieuticedutech.com/leadssheet
 *     → asks for the key, then does the same.
 *
 * The workbook is generated by the backend (routes/exportRoutes.js); this
 * page only forwards the request. Never indexed.
 */
const EXPORT_URL = 'https://maieutic-backend-production.up.railway.app/leadssheet';

const downloadUrl = (key) => `${EXPORT_URL}?key=${encodeURIComponent(key)}`;

const LeadsSheetPage = () => {
  const [params]              = useSearchParams();
  const keyFromUrl            = params.get('key') || '';
  const [key, setKey]         = useState('');
  const [started, setStarted] = useState(false);

  // Direct URL with a key: start the download immediately.
  useEffect(() => {
    if (keyFromUrl) {
      setStarted(true);
      window.location.replace(downloadUrl(keyFromUrl));
    }
  }, [keyFromUrl]);

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!key.trim()) return;
    setStarted(true);
    window.location.assign(downloadUrl(key.trim()));
  };

  return (
    <>
      <Helmet>
        <title>Leads Sheet Download | Maieutic Edutech Private Limited</title>
        <meta name="robots" content="noindex, nofollow" />
      </Helmet>
      <div style={{
        minHeight: '100vh', background: 'linear-gradient(135deg, #00615c, #004d49)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        fontFamily: "'Poppins', sans-serif", padding: '24px',
      }}>
        <div style={{
          background: '#fff', borderRadius: '20px', padding: '48px 40px',
          width: '90%', maxWidth: '440px', boxShadow: '0 30px 80px rgba(0,0,0,0.25)',
          textAlign: 'center',
        }}>
          <p style={{ fontSize: '11px', fontWeight: 700, letterSpacing: '3px', color: '#800d07', textTransform: 'uppercase', marginBottom: '10px' }}>
            MAIEUTIC EDUTECH
          </p>
          <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: '28px', color: '#00615c', fontWeight: 700, marginBottom: '8px' }}>
            Leads Sheet
          </h1>

          {started ? (
            <>
              <p style={{ fontSize: '14px', color: '#555', lineHeight: 1.6, marginBottom: '20px' }}>
                Your download should start in a moment. It contains four sheets:
                Apply Now, Contact Us, Enquire Now and Lead Popup.
              </p>
              <p style={{ fontSize: '13px', color: '#888', lineHeight: 1.6 }}>
                If nothing happened, the key may be wrong.{' '}
                <a href="/leadssheet" style={{ color: '#800d07', fontWeight: 600 }}>Try again</a>
              </p>
            </>
          ) : (
            <>
              <p style={{ fontSize: '14px', color: '#888', lineHeight: 1.6, marginBottom: '28px' }}>
                Enter the access key to download the Excel workbook of all form submissions.
              </p>
              <form onSubmit={handleSubmit}>
                <input
                  type="password"
                  value={key}
                  onChange={(e) => setKey(e.target.value)}
                  placeholder="Access key"
                  autoFocus
                  style={{
                    width: '100%', padding: '12px 14px', marginBottom: '16px',
                    border: '2px solid #e0e0e0', borderRadius: '8px',
                    fontFamily: "'Poppins', sans-serif", fontSize: '14px',
                    outline: 'none', boxSizing: 'border-box',
                  }}
                  onFocus={(e) => { e.target.style.borderColor = '#00615c'; }}
                  onBlur={(e) => { e.target.style.borderColor = '#e0e0e0'; }}
                />
                <button type="submit" style={{
                  width: '100%', padding: '13px',
                  background: '#800d07', border: 'none', borderRadius: '8px',
                  fontFamily: "'Poppins', sans-serif", fontSize: '15px',
                  fontWeight: 700, color: '#fff', cursor: 'pointer',
                }}>
                  ⬇ Download Excel
                </button>
              </form>
            </>
          )}
        </div>
      </div>
    </>
  );
};

export default LeadsSheetPage;
